name: Deploy

on:
  workflow_dispatch:
    inputs:
      chart:
        description: 'Helm chart name'
        required: true
        default: 'python-hello-world'
      version:
        description: 'Helm chart version'
        required: true
        default: '0.1.0'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch history
      run: git fetch --prune --unshallow
    - name: Add Helm repo
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          helm repo add kjg 'https://${{ secrets.CR_TOKEN }}@raw.githubusercontent.com/karl-johan-grahn/private-helm-registry/gh-pages/'
    - name: Update repo
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          helm repo update
    - name: Install chart
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          helm --debug install ${{ github.event.inputs.chart }} kjg/${{ github.event.inputs.chart }} --version ${{ github.event.inputs.version }} --username ${{ secrets.GH_USERNAME }} --password ${{ secrets.CR_TOKEN }}
