name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
  test-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          node_image: kindest/node:v1.18.8
        # Only build a kind cluster if there are chart changes to test
        if: steps.lint.outputs.changed == 'true'
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install